name: server-ci
on:
  push:
    paths:
      - "apps/game-server/**"
      - ".github/workflows/server.yml"
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        working-directory: apps/game-server
        run: npm ci || npm i
      - name: Typecheck & build
        working-directory: apps/game-server
        run: npm run build
