name: web-netlify-preview
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: apps/web
